### ISSUE TITLE
OpenAI chat completion replies are truncated if 2000 character limit is exceeded

### ISSUE THREAD

**Issue by ghost** [mordoprojekt/mordoprojekt#18]
## Expected behaviour 
Entire chat completion message is displayed.

## Actual behaviour 
The message is being truncated at 2000 character length.

**Comment by mrozonn** [comment]
fixed in commit 3136f884d6b75ecb35882a85bd53e8356cd6873c, 

changed method to embed (max 4096 characters) and came to consensus that there is no need for implementing message splitting method, as ChatGPT will not generate text longer than 4096 characters due to limits

closing as fixed
